# Generated by Django 5.1.6 on 2025-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_image', models.ImageField(upload_to='reviews/', verbose_name='Фото покупателя')),
                ('reviewer_name', models.CharField(max_length=80, verbose_name='Имя покупателя')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('review_stars', models.IntegerField(verbose_name='Количество звезд')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
